home:
    path:  /
    defaults: { _controller: app.controller.main:homeAction }

start_session:
    path:  /start-session
    defaults: { _controller: app.controller.main:startSessionAction }

# question
question_detail:
    path:  /vraag/{id}/{answer}
    defaults: { _controller: app.controller.question:detailAction, answer: null }

# user
user_login:
    path:  /inloggen
    defaults: { _controller: app.controller.user:loginAction }

user_consumption:
    path:  /voor-wie-haal-je-koffie
    defaults: { _controller: app.controller.user:consumptionAction }

user_logout:
    path:  /uitloggen
